### ISSUE TITLE
训练速度和Loss变NaN

### ISSUE THREAD

**Issue by yihjian** [bubbliiiing/yolo3-keras#11]
发现训练速度很慢，~10000 sample的情况下一个epoch要接近20分钟(~1100s)。任务管理器显示显存≈7.6/8G，但是运算占用就百分之几，CPU占用也不高。推测是data_generate里单线程做augmentation出了瓶颈，因为在服务器上四块V100跑占用也上不去。然后训练到10个epoch上下出现了Loss NaN，翻了一下其他implementation里的issue，有提到说bad sample/改小lr一类的（有点随机性），不知道作者大大有无想法。

**Comment by bubbliiiing** [comment]
fitgenerator不是可以设置workers啥的么。我没有这么多显卡，LOSS变NAN我没有出现过，

**Comment by yihjian** [comment]
非常神奇，开workers在服务器上能跑但是本地机子pickle报错了。我试了下用tf.dataset.from_generator，output type和shape一直调不好。
anyway在服务器上炼出来了，谢谢作者大大
