### ISSUE TITLE
运行get_dr_txt.py没报错但是没结果是怎么回事，急

### ISSUE THREAD

**Issue by QISIRUI** [bubbliiiing/yolo3-keras#25]
`0it [00:00, ?it/s]
Conversion completed!

Process finished with exit code 0`
就这样然后没了

**Comment by QISIRUI** [comment]
公开的数据集有结果，自己的数据集就不行了，yolov4公开的数据集也不行

**Comment by bubbliiiing** [comment]
嗯啊？格式不对吧
